
##
##	Flying Spaghetti Monster by T-101 / Primitive
##
##	Yells out Flying Spaghetti Monster holidays
##	https://en.wikipedia.org/wiki/Flying_Spaghetti_Monster
##
##	Usage: !spaghetti		# usually this runs daily
##
##	You must set the "channels" variable to fit your needs
##	This script will shout out to all of them
##
##	set "announceHour" and "announceMinute" variables
##	to your liking (24 hour clock)
##
##	Use at own risk
##
##	2020 | primitive.be | IRCNet
##
##
##	Version history:
##		1.0.0	-	Initial release

namespace eval ::spaghetti {
##  Add channels here. You can add multiple, just divide them with a whitespace
    set channels "#justsesunkanava"

##	Change daily hour HERE
    set announceHour 05
    set announceMinute 01

##
##	After this, here be dragons
##

    set spaghettiVersion 1.0.0

    bind time "$announceMinute $announceHour % % %" ::spaghetti::announce
    bind pub - !spaghetti ::spaghetti::announce

    proc getHoliday {} {
        set holidays {
            "1.1. Another Friggin Year Day"
            "2.1. Swiss Cheese Day"
            "3.1. Make Macaroni Pictures Day"
            "4.1. Spaghetti Day"
            "5.1. International Verbal Abuse Day"
            "6.1. Extra Cuddles Day"
            "7.1. No Knitting Day"
            "8.1. Bubble Bath Day"
            "9.1. Walk Like an Egyptian Day"
            "10.1. Peculiar People Day"
            "11.1. Spam Spam Spam Spam Spam Day"
            "12.1. Penne in Your Thoughts Day"
            "13.1. Sceptics Day"
            "14.1. Wear a Collander Day"
            "15.1. Unicorn Day"
            "16.1. Nothingness Appreciation Day"
            "17.1. International No Farting Day"
            "18.1. Egg Juggling Day"
            "19.1. Procrastination Day Tomorrow"
            "20.1. Marx Brothers Quote Day"
            "21.1. Ravioli Day"
            "22.1. Quantum Cheese Day"
            "23.1. Get Your Tongue Round Some Linguine Day"
            "24.1. Invent a God Day"
            "25.1. Burns Night"
            "26.1. String Appreciation Day"
            "27.1. Llama Day"
            "28.1. Black Pepper with Everything Day"
            "29.1. Curmudgeons Day"
            "30.1. Exercise Your Brain Day"
            "31.1. Honey Badger Avoidance Day"
            "1.2. Fettucine February"
            "2.2. Groundhog Day"
            "3.2. Ewok Day"
            "4.2. Annoy the Neighbours Day"
            "5.2. Doodle Day"
            "6.2. Self-love Day"
            "7.2. No-Day Day"
            "8.2. Avoid Artichokes Day"
            "9.2. Extraterestial Culture Day"
            "10.2. Paradox Day"
            "11.2. Hide Under the Bed Day"
            "12.2. Darwin Day"
            "13.2. Tortellini Day"
            "14.2. Pretend to be Romantic Day"
            "15.2. Drink More Wine Day"
            "16.2. Platypus Pondering Day"
            "17.2. Hopping Day"
            "18.2. Navel Appreciation Day"
            "19.2. Lentil Sauce Day"
            "20.2. Levitation Day"
            "21.2. Talk to a Goldfish Day"
            "22.2. Appreciate Dragons Day"
            "23.2. Remember the Alamo Day"
            "24.2. Carthaginian Ghost Spotting Day"
            "25.2. Octopus Enjoyment Day"
            "26.2. Lost Pen Day"
            "27.2. Silly Hat Day"
            "28.2. Evil Clown Day"
            "29.2. Refuse to believe in this day day"
            "1.3. Narwhal Day"
            "2.3. Tagliatelle Day"
            "3.3. Mulled Wine Day"
            "4.3. Random Day"
            "5.3. Momofuku Ando's Birthday"
            "6.3. Fusilli Day"
            "7.3. Contradiction Day (No it's not!)"
            "8.3. Annie Bonny's Birthday"
            "9.3. Meatball Day"
            "10.3. Wooden Leg Polishing Day"
            "11.3. Douglas Adams Birthday"
            "12.3. Cuddle an Accountant Day"
            "13.3. Cthulhu Contemplation Day"
            "14.3. Pi Day"
            "15.3. Aardvark Appreciation Day"
            "16.3. Kinky Underwear Day"
            "17.3. St. Patricks Day Excuse"
            "18.3. Vodka Day"
            "19.3. Beer Appreciation Day"
            "20.3. Extraterrestrial Abductions Day"
            "21.3. French Bread Day"
            "22.3. Slightly Silly Day"
            "23.3. Pansexual Quantum Toaster Day"
            "24.3. Red Wine Day"
            "25.3. Manatee Appreciation Day"
            "26.3. Make Up Your Own Holiday Day"
            "27.3. Paella Day"
            "28.3. Garden Weeds Appreciation Day"
            "29.3. Cocktail Hour Every Hour Day"
            "30.3. Poke Things with a Pencil Day"
            "31.3. Survived Another Month Day"
            "1.4. All Fools Day"
            "2.4. Existential Angst Day"
            "3.4. Seize a Sausage Day"
            "4.4. Feast of No Saints Day"
            "5.4. Pizza Day"
            "6.4. Impersonate a Frog Day"
            "7.4. Inner Wombat Appreciation Day"
            "8.4. Zoo Day"
            "9.4. Cook Couscous Day"
            "10.4. Alfredo Sauce Day"
            "11.4. Cheese Fondue Day"
            "12.4. Naughty Noodle Day"
            "13.4. Believe in Fairies Day"
            "14.4. Look up at the Sky Day"
            "15.4. Banana Day"
            "16.4. Sea Monkey Soup Day"
            "17.4. Haiku Day"
            "18.4. Nihilism Day"
            "19.4. Lager Day"
            "20.4. Intergalactic Alien Solidarity Day"
            "21.4. Eggnog Avoidance Day"
            "22.4. Earth Day"
            "23.4. Cynical Bastards Day"
            "24.4. Hairball Awareness Day"
            "25.4. World Penguin Day"
            "26.4. Hug an Australian Day"
            "27.4. 8640 Seconds Day"
            "28.4. Blueberry Pie Day"
            "29.4. Dance Day"
            "30.4. Achieve Enlightenment Day"
            "31.4. Masturbating Yak Day"
            "1.5. No Pants Day"
            "2.5. Ramen Day"
            "3.5. Pirate Garb Day"
            "4.5. Star Wars Day"
            "5.5. Ferret Day"
            "6.5. Beverage Day"
            "7.5. Scurvy Awareness Day"
            "8.5. Back Scratching Day"
            "9.5. Lost Sock Memorial Day"
            "10.5. Wolverine Day"
            "11.5. Salvador Dali Day"
            "12.5. Limerick Day"
            "13.5. Buttocks Day"
            "14.5. International Monty Python Day"
            "15.5. Bike to Work Day"
            "16.5. Skinny Dipping Day"
            "17.5. Single Malt Whisky Day"
            "18.5. Russell's Teapot Day"
            "19.5. Bolognese Sauce Day"
            "20.5. Fetish Day"
            "21.5. 42 Day"
            "22.5. Biological Diversity Day"
            "23.5. Turtle Day"
            "24.5. Mollusc Day"
            "25.5. Towel Day"
            "26.5. World Hunger Day"
            "27.5. Weasel Tossing Day"
            "28.5. Amnesty International Day"
            "29.5. Pillow Fight Day"
            "30.5. Random Act of Kindness Day"
            "31.5. Insect Appreciation Day"
            "1.6. Go Barefoot Day"
            "2.6. Laugh Like a Bad Guy Day"
            "3.6. Mushroom Sauce Day"
            "4.6. Cougar Day"
            "5.6. Doughnut Day"
            "6.6. Adopt a New Phobia day"
            "7.6. Captain Jack Sparrow Impersonation Day"
            "8.6. Be Annoyingly Cheerful Day"
            "9.6. Bathe in Marinara Day"
            "10.6. Flirting Day"
            "11.6. Fish Day"
            "12.6. Be Paranoid Day"
            "13.6. Gin Day"
            "14.6. Bourbon Day"
            "15.6. Bad Joke Day"
            "16.6. World Meat-free Day"
            "17.6. Contact an Old Friend Day"
            "18.6. Now Panic Day"
            "19.6. Martini Day"
            "20.6. World Juggling Day"
            "21.6. World Humanist Day"
            "22.6. Marinara Sauce Day"
            "23.6. Parrot Pondering Day"
            "24.6. Sexual Fantasy Day"
            "25.6. Seafarer Day"
            "26.6. Carbonara Day"
            "27.6. Blue-Footed Booby Day"
            "28.6. Tickle Day"
            "29.6. Knitting Day"
            "30.6. Just Another Day Day"
            "1.7. Any Bloody Excuse Day"
            "2.7. Pesto Sauce Day"
            "3.7. Strange Urges Day"
            "4.7. Build a Scarecrow Day"
            "5.7. Impersonate an Orc Day"
            "6.7. Macaroni Day"
            "7.7. Cannelloni Day"
            "8.7. Meatball Appreciation Day"
            "9.7. Invent a Word Day"
            "10.7. Pina Colada Day"
            "11.7. World Population Day"
            "12.7. Surrealism Day"
            "13.7. Geek Appreciation Day"
            "14.7. Cow Appreciation Day"
            "15.7. Ferret Down Your Trousers Day"
            "16.7. Bobby Henderson's Birthday"
            "17.7. Why Not? Day"
            "18.7. Waterpistol Day"
            "19.7. Daiquiri Day"
            "20.7. National Lasagne Day"
            "21.7. Primavera Sauce Day"
            "22.7. Contemplate the Cosmos Day"
            "23.7. Free Hugs Day"
            "24.7. Tequila Day"
            "25.7. Hot Fudge Sundae Day"
            "26.7. White Wine Day"
            "27.7. Confuse a Cat Day"
            "28.7. Try a New Cheese Day"
            "29.7. International Beer Day"
            "30.7. Parmesan Day"
            "31.7. Real Ale Day"
            "1.8. Cartoon Day"
            "2.8. Vermicelli Day"
            "3.8. Postmodernism Day"
            "4.8. Mead Day"
            "5.8. Putanesca Sauce Day"
            "6.8. Squirrel Spotting Day"
            "7.8. International Beer Day"
            "8.8. International Cat Day"
            "9.8. Invisible Pixy Swatting Day"
            "10.8. Lazy Day"
            "11.8. Rum Day"
            "12.8. Vegetable Sauce Day"
            "13.8. Listen To Reggae Day"
            "14.8. Think about Infinity Day"
            "15.8. Condom Day"
            "16.8. Wave At The Surveillance Cameras Day"
            "17.8. Gnocchi Gnawing day."
            "18.8. Poetry Day"
            "19.8. Kiss Someone Day"
            "20.8. Expensive Rum Day"
            "21.8. Apologise Day"
            "22.8. Tarantula Teasing Day"
            "23.8. Appreciate What You've Got Day"
            "24.8. Pluto Demotion Grieving Day"
            "25.8. Whiskey Sour Day"
            "26.8. Women's Equality Day"
            "27.8. Udon Day"
            "28.8. More Rum Day"
            "29.8. Blobfish Day"
            "30.8. Candle in a Winebottle Day"
            "31.8. Alter Ego Day"
            "1.9. Hobbit Remembrance Day"
            "2.9. Nipple Appreciation Day"
            "3.9. World No Haggis Day"
            "4.9. Rock Appreciation Day"
            "5.9. Yodelling Day"
            "6.9. Diablo Sauce Day"
            "7.9. Old Boy/Girlfiends Remembrance Day"
            "8.9. Paradoxically Non-paradoxical Day"
            "9.9. Ogle an Orchid Day"
            "10.9. Albatross Appreciation Day"
            "11.9. Tinfoil Hat Day"
            "12.9. Nakedness Appreciation Day"
            "13.9. Mosquito Avoidance Day"
            "14.9. Despair for the Human Race Day"
            "15.9. Irish Coffee Day"
            "16.9. Cynicism Appreciation Day"
            "17.9. Wear Purple Day"
            "18.9. Sophia Loren's Appreciation Day"
            "19.9. International Talk Like a Pirate Day"
            "20.9. Amoeba Assimilation Day"
            "21.9. Sarcasm Day"
            "22.9. Believe the Impossible Day"
            "23.9. Albino Appreciation Day"
            "24.9. Cocktail Day"
            "25.9. Any Port & Lemon in a Storm Day"
            "26.9. Scrub the Poop Deck Day"
            "27.9. Insult a Narcissist Day"
            "28.9. Fictional Character Day"
            "29.9. Double Entendre Day"
            "30.9. Plan for 31st Sept Day"
            "1.10. Agnolotti Appreciation Day"
            "2.10. Noodle Day"
            "3.10. Eccentricity Appreciation Day"
            "4.10. Fortified Wines Day"
            "5.10. Slighlty Naughty Day"
            "6.10. International Pastafarian Headgear Day"
            "7.10. Quob Day"
            "8.10. Tell Massive Lies Day"
            "9.10. Knot Day"
            "10.10. Dildo Day"
            "11.10. Play Nice Day"
            "12.10. Wanting Wonton Day"
            "13.10. Arrabiata Sauce Day"
            "14.10. World Food Day"
            "15.10. Another Noodle Day"
            "16.10. Blue Whale Contemplation Day"
            "17.10. World Pasta Day"
            "18.10. Irony Day"
            "19.10. Try Not to Die Day"
            "20.10. To Excess and No Further Day"
            "21.10. Try Thinking Day"
            "22.10. Intergalactic Peeing Competition"
            "23.10. Strip for your Lover Day"
            "24.10. Cider Appreciation Day"
            "25.10. World Pasta Day"
            "26.10. Silly Walks Day"
            "27.10. Clam Sauce Day"
            "28.10. Extra Kinky Day"
            "29.10. Nut Day"
            "30.10. Halloween"
            "31.10. Gerbil Caressing Day"
            "1.11. Moustache Appreciation Day"
            "2.11. Rigatoni Day"
            "3.11. Kissing Frogs Day"
            "4.11. Not the Zombie Apocalypse Day"
            "5.11. Oral Sex Day"
            "6.11. Dodo Grieving Day"
            "7.11. Tentacle Day"
            "8.11. Appreciate Your Loved Ones Day"
            "9.11. Odd Socks Day"
            "10.11. Look on the Bright Side of Life Day"
            "11.11. Small Furry Creatures Appreciation Day"
            "12.11. Drunk Creation Contemplation Day"
            "13.11. Punch a Pigeon Day"
            "14.11. Laugh like a Lunatic Day"
            "15.11. Awkwardly Honest Day"
            "16.11. Extinct Species Memorial Day"
            "17.11. Al Dente Day"
            "18.11. Talk like Donald Duck Day"
            "19.11. World Toilet Day"
            "20.11. Say no to Cannibalism Day"
            "21.11. Register a Complaint Day"
            "22.11. Blackbeard Memorial Day"
            "23.11. General Debauchery Day"
            "24.11. Undead Understanding Day"
            "25.11. Lucy the Australopithecine Discovery Day"
            "26.11. Racist Depreciation Day"
            "27.11. Grog Guzzling Day"
            "28.11. Blue Cheese Day"
            "29.11. Cutlass Sharpening Day"
            "30.11. Gnome Awareness Day"
            "1.12. Marijuana Sauce Day"
            "2.12. Fart Like a Pirate Day"
            "3.12. International Say No to Selfies Day"
            "4.12. Vibrator Day"
            "5.12. Remember the Spanish Inquisition Day"
            "6.12. Pirate Appreciation Day"
            "7.12. Still Not Dead Day"
            "8.12. Garlic Bread Day"
            "9.12. Noodle Ring Day"
            "10.12. International Human Rights Day"
            "11.12. International Shareware Day"
            "12.12. Ice Cream Day"
            "13.12. Monkey Day"
            "14.12. Cat Herders Day"
            "15.12. Stupid Toy Day"
            "16.12. Beethoven's Birthday"
            "17.12. Sloth Day"
            "18.12. Underdog Day"
            "19.12. Dalek Remembrance Day"
            "20.12. Swashbuckling Day"
            "21.12. Saturnalia"
            "22.12. Marco Polo Day"
            "23.12. Festivus"
            "24.12. Egg Nog Day"
            "25.12. 1st Day of Noodlemas"
            "26.12. Cardbard Box Appreciation Day"
            "27.12. 3rd Day of Noodlemas"
            "28.12. Only 4 Pasta-eating Days Left This Year Day"
            "29.12. Yad sdrawckab"
            "30.12. Get Drunk Early for Hogmanay"
            "31.12. Hogmanay"
            "32.12. You're Drunk!"
        }
        set date [clock format [clock seconds] -format {%d.%m.}]
        if {[lsearch $holidays ${date}*] != -1} {
            return [lrange [lindex $holidays [lsearch $holidays ${date}*]] 1 end]
        }
    }

    proc announce { args } {
        variable channels
        if {[string index [lindex $args 3] 0] == "#"} {
            # called via command
            set channelArg [lindex $args 3]
            foreach channel [split $channels] {
                if {[string tolower $channel] == [string tolower $channelArg]} {
                    putquick "NOTICE $channel :Pastafarianism: [getHoliday]"
                }
            }
        } else {
            # called via cron
            foreach channel [split $channels] {
                putquick "NOTICE $channel :Pastafarianism: [getHoliday]"
            }
        }
    }

    putlog "fsm.tcl $spaghettiVersion by T-101 loaded!"

}